apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: vm-cloud-storage-object-admin
spec:
  member: serviceAccount:kfp-standalone-1-vm@kfp-ci.iam.gserviceaccount.com # {"$kpt-set":"vm-sa-ref"}
  # This allows tests to:
  # * get/put cloud storage objects
  # * pull/push cloud container registry images
  role: roles/storage.objectAdmin
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: projects/kfp-ci # {"$kpt-set":"project-ref"}
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: vm-viewer
spec:
  member: serviceAccount:kfp-standalone-1-vm@kfp-ci.iam.gserviceaccount.com # {"$kpt-set":"vm-sa-ref"}
  # This allows tests to list storage buckets.
  # Reference: https://cloud.google.com/storage/docs/access-control/iam-roles#basic-roles-intrinsic
  role: roles/viewer
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: projects/kfp-ci # {"$kpt-set":"project-ref"}
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: vm-dataflow-admin
spec:
  member: serviceAccount:kfp-standalone-1-vm@kfp-ci.iam.gserviceaccount.com # {"$kpt-set":"vm-sa-ref"}
  # This allows the following sample to create dataflow jobs:
  # https://github.com/kubeflow/pipelines/blob/f4a37b27ec5950310a76943e1ff68289b9c40d7d/samples/core/dataflow/dataflow.ipynb
  # Reference: https://cloud.google.com/iam/docs/understanding-roles#dataflow-roles
  role: roles/dataflow.admin
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: projects/kfp-ci # {"$kpt-set":"project-ref"}
